// Kuwait Governorates
export const KUWAIT_GOVERNORATES = [
  'Al Asimah (Capital)',
  'Hawalli',
  'Farwaniya',
  'Mubarak Al-Kabeer',
  'Ahmadi',
  'Jahra',
];

// Kuwait Areas by Governorate
export const KUWAIT_AREAS = {
  'Al Asimah (Capital)': [
    'Kuwait City',
    'Sharq',
    'Mirqab',
    'Dasman',
    'Salhiya',
    'Qibla',
    'Jibla',
    'Dasma',
    'Bneid Al-Gar',
    'Mansouriya',
    'Abdullah Al-Salem',
    'Nuzha',
    'Faiha',
    'Shamiya',
    'Rawda',
    'Adailiya',
    'Khaldiya',
    'Kaifan',
    'Qurtuba',
    'Surra',
    'Yarmouk',
    'Shuwaikh',
    'Doha',
    'Ghornata',
  ],
  'Hawalli': [
    'Hawalli',
    'Nugra',
    'Salmiya',
    'Salwa',
    'Rumaithiya',
    'Mishref',
    'Bayan',
    'Jabriya',
    'Zahra',
    'Shaab',
    'Maidan Hawalli',
    'Hitteen',
    'Shuhada',
    'Sideeq',
    'Hateen',
  ],
  'Farwaniya': [
    'Farwaniya',
    'Khaitan',
    'Jleeb Al-Shuyoukh',
    'Hassawi',
    'Rabiya',
    'Riggae',
    'Andalous',
    'Omariya',
    'Firdous',
    'Sabah Al-Nasser',
    'Abdullah Al-Mubarak',
    'Ishbiliya',
    'Rehab',
    'Airport Area',
  ],
  'Mubarak Al-Kabeer': [
    'Mubarak Al-Kabeer',
    'Adan',
    'Qurain',
    'Qusour',
    'Sabah Al-Salem',
    'Messila',
    'Abu Fatira',
    'Abu Al-Hasaniya',
    'Funaitees',
    'West Abu Fatira',
  ],
  'Ahmadi': [
    'Ahmadi',
    'Fahaheel',
    'Mangaf',
    'Mahboula',
    'Fintas',
    'Abu Halifa',
    'Egaila',
    'Sabahiya',
    'Riqqa',
    'Hadiya',
    'Jaber Al-Ali',
    'Fahad Al-Ahmad',
    'Ali Sabah Al-Salem',
    'Wafra',
    'Zour',
    'Shuaiba',
    'Mina Abdullah',
    'Bnaider',
    'Julaia',
  ],
  'Jahra': [
    'Jahra',
    'Waha',
    'Qasr',
    'Naseem',
    'Taima',
    'Oyoun',
    'Sulaibiya',
    'Amghara',
    'Saad Al-Abdullah',
    'Sulaibikhat',
    'Doha',
    'Nahda',
    'Qairawan',
    'South Doha',
    'Abdali',
    'Salmi',
    'Kabd',
  ],
};

export default { KUWAIT_GOVERNORATES, KUWAIT_AREAS };
