#!/bin/sh
set -eu

command -v docker >/dev/null 2>&1 || {
  echo "Docker-compatible container runtime is required." >&2
  exit 1
}

npm ci
npx supabase start
npx supabase db reset --local

status_file=$(mktemp)
trap 'rm -f "$status_file"' EXIT
npx supabase status -o env > "$status_file"

# The status output contains shell-safe assignments generated by the CLI.
# shellcheck disable=SC1090
. "$status_file"

publishable_key=${PUBLISHABLE_KEY:-${ANON_KEY:-}}
if [ -z "$publishable_key" ]; then
  echo "Supabase status did not return a publishable or anon key." >&2
  exit 1
fi

umask 077
{
  echo "VITE_APP_ENV=development"
  echo "VITE_APP_URL=http://127.0.0.1:5173"
  echo "VITE_SUPABASE_URL=${API_URL:-http://127.0.0.1:54321}"
  echo "VITE_SUPABASE_PUBLISHABLE_KEY=$publishable_key"
} > .env.local

if [ ! -f supabase/functions/.env.local ]; then
  cp supabase/functions/.env.example supabase/functions/.env.local
  chmod 600 supabase/functions/.env.local
fi

echo "Local environment is ready. Run: npm run local:start"

